# ---------------------------------------------------------------------------
# External Dependencies:
# spring-boot (org.springframework.boot) version 3.1.0
# spring-data-mongodb (org.springframework.data.mongodb) version 3.1.0
# spring-kafka (org.springframework.kafka) version 2.8.0
# micrometer-registry-prometheus (io.micrometer) version 1.9.0
# ---------------------------------------------------------------------------

spring:
  application:
    name: booking-service
  data:
    mongodb:
      host: "${MONGODB_HOST:localhost}"
      port: "${MONGODB_PORT:27017}"
      database: "${MONGODB_DATABASE:dogwalking_bookings}"
      username: "${MONGODB_USERNAME}"
      password: "${MONGODB_PASSWORD}"
      authentication-database: "admin"
      auto-index-creation: true
      connection-pool:
        max-size: 50
        min-size: 5
        max-wait-time: 5000
        max-connection-life-time: 30000
    kafka:
      bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}"
      consumer:
        group-id: "booking-service"
        auto-offset-reset: "latest"
        key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
        value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      producer:
        key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
        value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      topics:
        booking-events: "booking-events"
        booking-status-updates: "booking-status-updates"

server:
  port: "${SERVER_PORT:8082}"
  servlet:
    context-path: "/api/v1/bookings"
  compression:
    enabled: true
    mime-types:
      - "application/json"
      - "application/xml"
      - "text/plain"

management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "metrics"
          - "prometheus"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: "booking-service"

logging:
  level:
    root: "INFO"
    com.dogwalking.booking: "DEBUG"
    org.springframework.data.mongodb: "INFO"
    org.apache.kafka: "INFO"
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"