#------------------------------------------------------------------------------
# Elasticsearch configuration file for centralized logging and monitoring
# in the Dog Walking Application's ELK stack.
#
# External Dependencies (IE2: Library Versions):
#   - elasticsearch (v8.11.1): Core functionalities for cluster, indexing, and search
#   - x-pack (v8.11.1): Advanced features including security, monitoring, and RBAC
#
# Internal Imports (IE1):
#   - logstash_config.monitoring_settings (from infrastructure/monitoring/elk/logstash.yml)
#     Integration with Logstash monitoring settings for unified ELK stack
#
# Exports (IE3):
#   - elasticsearch_config (named YAML export)
#       • cluster_settings
#       • network_settings
#       • security_settings
#
# This file must implement:
#   1) System Monitoring (2.4.1) via X-Pack monitoring
#   2) Cross-Cutting Concerns (2.4) through secure transport and advanced configuration
#   3) High Availability (2.5.1) with multi-node cluster setup
#
# Style & Usage:
#   - Extensive comments for clarity (S2)
#   - Production-ready and enterprise-grade configuration
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# cluster_settings: (Exported Section)
#------------------------------------------------------------------------------
# High-availability cluster configuration. Each node can serve multiple roles:
# master, data, and ingest. The cluster name must match across all nodes.
cluster.name: "dogwalking-monitoring"
node.name: "${HOSTNAME}"
node.roles: ["master", "data", "ingest"]

# For older versions of Elasticsearch, setting node.master/data/ingest to true
# was standard. Though node.roles is often sufficient in ES 8.x, we align with
# the specification for clarity and compatibility.
node.master: true
node.data: true
node.ingest: true

#------------------------------------------------------------------------------
# path_settings:
#------------------------------------------------------------------------------
# Filesystem paths for storing data and logs. Ensure these directories have
# necessary permissions and sufficient disk space.
path.data: "/usr/share/elasticsearch/data"
path.logs: "/usr/share/elasticsearch/logs"

#------------------------------------------------------------------------------
# network_settings: (Exported Section)
#------------------------------------------------------------------------------
# Network binding and discovery settings. The 'discovery.seed_hosts' should list
# other nodes' hostnames or IPs for cluster formation. 'cluster.initial_master_nodes'
# is needed for a fresh cluster startup to elect master nodes.
network.host: "0.0.0.0"
http.port: 9200
transport.port: 9300

discovery.seed_hosts:
  - "elasticsearch-0.elasticsearch"
  - "elasticsearch-1.elasticsearch"
  - "elasticsearch-2.elasticsearch"

cluster.initial_master_nodes:
  - "elasticsearch-0"
  - "elasticsearch-1"
  - "elasticsearch-2"

#------------------------------------------------------------------------------
# security_settings: (Exported Section)
#------------------------------------------------------------------------------
# X-Pack security configuration with TLS/SSL for transport layer security.
# The settings below assume certificates are provided via .p12 stores.
xpack.security.enabled: true

# Transport layer SSL ensures secure node-to-node communication within the cluster.
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: "certificate"
xpack.security.transport.ssl.keystore.path: "elastic-certificates.p12"
xpack.security.transport.ssl.truststore.path: "elastic-certificates.p12"

#------------------------------------------------------------------------------
# monitoring_settings:
#------------------------------------------------------------------------------
# Comprehensive monitoring configuration. Aligns with Logstash's
# xpack.monitoring settings for a unified telemetry approach.
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true
xpack.monitoring.elasticsearch.collection.enabled: true

# Defines how frequently monitoring metrics are gathered (2.4.1).
xpack.monitoring.collection.interval: "10s"

#------------------------------------------------------------------------------
# memory_settings:
#------------------------------------------------------------------------------
# Optimized memory usage for production workloads. Ensure that JVM heap sizing
# is also configured via ES_JAVA_OPTS in the container or system environment.
bootstrap.memory_lock: true
indices.memory.index_buffer_size: "30%"
indices.queries.cache.size: "5%"
indices.fielddata.cache.size: "20%"

#------------------------------------------------------------------------------
# End of elasticsearch.yml configuration
#------------------------------------------------------------------------------