# -----------------------------------------------------------------------------------
# Kubernetes Namespaces for the Dog Walking Platform
# This file is validated against Kubernetes v1.28 for advanced resource definitions,
# ensuring service isolation, security, and high availability in compliance with SOC2 and GDPR.
# -----------------------------------------------------------------------------------
apiVersion: v1
kind: List
items:
  # -----------------------------------------------------------------------------
  # Namespace: api-gateway
  # -----------------------------------------------------------------------------
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: api-gateway
      labels:
        # Human-readable label for this namespace
        name: api-gateway
        # Identifies the component role within the platform
        component: gateway
        # Indicates which larger application it belongs to
        part-of: dog-walking-platform
        # Tier classification for resource grouping (frontend, backend, etc.)
        tier: frontend
        # Dynamic environment placeholder for flexible deployment (e.g., dev, prod)
        environment: "${ENV}"
        # Versioning to track changes for multi-stage rollouts
        version: "v1"
        # Ownership label indicating administrative responsibility
        managed-by: platform-team
      annotations:
        # Signifies that this namespace is critical from a security standpoint
        security.platform.io/critical: "true"
        # Enables automatic metrics scraping for this namespace
        monitoring.platform.io/scrape: "true"

  # -----------------------------------------------------------------------------
  # Namespace: auth-service
  # -----------------------------------------------------------------------------
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: auth-service
      labels:
        # Human-readable label for this namespace
        name: auth-service
        # Identifies that this component is part of the backend service layer
        component: backend
        # Indicates which larger application it belongs to
        part-of: dog-walking-platform
        # Tier classification reflecting enhanced security priority
        tier: security
        # Dynamic environment placeholder for environment-specific resources
        environment: "${ENV}"
        # Version label to facilitate controlled updates
        version: "v1"
        # Managed by the dedicated security team for more granular access control
        managed-by: security-team
      annotations:
        # Marks this namespace as critical for security audits and controls
        security.platform.io/critical: "true"
        # Enables metric collection to assist with real-time threat detection
        monitoring.platform.io/scrape: "true"
        # Ensures configured backup processes target this namespace
        backup.platform.io/enabled: "true"