###################################################################################################
# Kubernetes Secrets Manifest
# This file defines sensitive configuration data and credentials for all microservices
# in the Dog Walking Platform. Each Secret is associated with a specific namespace, ensuring
# proper isolation and adherence to strict security controls, including encryption at rest,
# TLS in transit, and automated key rotation. Annotations enable transparent auditing, backup
# policy enforcement, and real-time security monitoring.
#
# Built and validated for Kubernetes v1.28
# - AES-256-GCM with KMS for data at rest
# - TLS 1.3 for data in transit
# - Scheduled rotation every 30 days (720h)
# - RBAC and network policies set to strict
# - Daily backup with 90-day retention
###################################################################################################
apiVersion: v1
kind: List
items:
  #################################################################################################
  # Secret: api-gateway-secrets
  # Stores credentials and certificates required by the API Gateway, including JWT signing keys,
  # API keys, and TLS configuration. Adheres to scheduled rotation and secure encryption protocols.
  #################################################################################################
  - apiVersion: v1
    kind: Secret
    metadata:
      name: api-gateway-secrets
      namespace: api-gateway
      labels:
        app: api-gateway
        component: gateway
        part-of: dog-walking-platform
        managed-by: platform-team
      annotations:
        rotation.kubernetes.io/trigger: "true"
        rotation.kubernetes.io/schedule: "720h"
        encryption.kubernetes.io/kms-key: "aws-kms-key-id"
        encryption.kubernetes.io/algorithm: "AES-256-GCM"
        encryption.kubernetes.io/provider: "AWS KMS"
        security-controls.io/in-transit: "TLS 1.3"
        security-controls.io/key-rotation: "30 days"
        security-controls.io/audit-logging: "enabled"
        security-controls.io/access-alerts: "enabled"
        security-controls.io/usage-analytics: "enabled"
        rbac-policies.io/enforced: "true"
        network-policies.io/level: "strict"
        backup.platform.io/enabled: "true"
        backup.platform.io/schedule: "daily"
        backup.platform.io/retention: "90 days"
    type: Opaque
    data:
      JWT_SECRET: "<base64>"
      API_KEYS: "<base64>"
      TLS_CERT: "<base64>"
      TLS_KEY: "<base64>"

  #################################################################################################
  # Secret: auth-service-secrets
  # Holds authentication-related secrets such as JWT keys, OAuth client IDs, and client secrets
  # for the Auth Service. Managed by the security team with maximum isolation and strict controls.
  #################################################################################################
  - apiVersion: v1
    kind: Secret
    metadata:
      name: auth-service-secrets
      namespace: auth-service
      labels:
        app: auth-service
        component: auth
        part-of: dog-walking-platform
        managed-by: security-team
      annotations:
        rotation.kubernetes.io/trigger: "true"
        rotation.kubernetes.io/schedule: "720h"
        encryption.kubernetes.io/kms-key: "aws-kms-key-id"
        encryption.kubernetes.io/algorithm: "AES-256-GCM"
        encryption.kubernetes.io/provider: "AWS KMS"
        security-controls.io/in-transit: "TLS 1.3"
        security-controls.io/key-rotation: "30 days"
        security-controls.io/audit-logging: "enabled"
        security-controls.io/access-alerts: "enabled"
        security-controls.io/usage-analytics: "enabled"
        rbac-policies.io/enforced: "true"
        network-policies.io/level: "strict"
        backup.platform.io/enabled: "true"
        backup.platform.io/schedule: "daily"
        backup.platform.io/retention: "90 days"
    type: Opaque
    data:
      JWT_SECRET: "<base64>"
      OAUTH_CLIENT_ID: "<base64>"
      OAUTH_CLIENT_SECRET: "<base64>"

  #################################################################################################
  # Secret: payment-service-secrets
  # Contains API keys and credentials used by the Payment Service to integrate with external
  # payment gateways. Data is encrypted and subject to automated key rotation for PCI compliance.
  #################################################################################################
  - apiVersion: v1
    kind: Secret
    metadata:
      name: payment-service-secrets
      namespace: payment-service
      labels:
        app: payment-service
        component: payment
        part-of: dog-walking-platform
        managed-by: platform-team
      annotations:
        rotation.kubernetes.io/trigger: "true"
        rotation.kubernetes.io/schedule: "720h"
        encryption.kubernetes.io/kms-key: "aws-kms-key-id"
        encryption.kubernetes.io/algorithm: "AES-256-GCM"
        encryption.kubernetes.io/provider: "AWS KMS"
        security-controls.io/in-transit: "TLS 1.3"
        security-controls.io/key-rotation: "30 days"
        security-controls.io/audit-logging: "enabled"
        security-controls.io/access-alerts: "enabled"
        security-controls.io/usage-analytics: "enabled"
        rbac-policies.io/enforced: "true"
        network-policies.io/level: "strict"
        backup.platform.io/enabled: "true"
        backup.platform.io/schedule: "daily"
        backup.platform.io/retention: "90 days"
    type: Opaque
    data:
      STRIPE_SECRET_KEY: "<base64>"
      PAYPAL_SECRET_KEY: "<base64>"

  #################################################################################################
  # Secret: booking-service-secrets
  # Specifies the database and cache connection strings for the Booking Service, ensuring that
  # scheduling and availability data remain secured and properly encrypted at rest.
  #################################################################################################
  - apiVersion: v1
    kind: Secret
    metadata:
      name: booking-service-secrets
      namespace: booking-service
      labels:
        app: booking-service
        component: booking
        part-of: dog-walking-platform
        managed-by: platform-team
      annotations:
        rotation.kubernetes.io/trigger: "true"
        rotation.kubernetes.io/schedule: "720h"
        encryption.kubernetes.io/kms-key: "aws-kms-key-id"
        encryption.kubernetes.io/algorithm: "AES-256-GCM"
        encryption.kubernetes.io/provider: "AWS KMS"
        security-controls.io/in-transit: "TLS 1.3"
        security-controls.io/key-rotation: "30 days"
        security-controls.io/audit-logging: "enabled"
        security-controls.io/access-alerts: "enabled"
        security-controls.io/usage-analytics: "enabled"
        rbac-policies.io/enforced: "true"
        network-policies.io/level: "strict"
        backup.platform.io/enabled: "true"
        backup.platform.io/schedule: "daily"
        backup.platform.io/retention: "90 days"
    type: Opaque
    data:
      DATABASE_URL: "<base64>"
      REDIS_URL: "<base64>"

  #################################################################################################
  # Secret: tracking-service-secrets
  # Contains configurations for the Tracking Service’s MQTT broker credentials, enabling secure
  # real-time location updates. Encrypted at rest with frequent rotation for reliability.
  #################################################################################################
  - apiVersion: v1
    kind: Secret
    metadata:
      name: tracking-service-secrets
      namespace: tracking-service
      labels:
        app: tracking-service
        component: tracking
        part-of: dog-walking-platform
        managed-by: platform-team
      annotations:
        rotation.kubernetes.io/trigger: "true"
        rotation.kubernetes.io/schedule: "720h"
        encryption.kubernetes.io/kms-key: "aws-kms-key-id"
        encryption.kubernetes.io/algorithm: "AES-256-GCM"
        encryption.kubernetes.io/provider: "AWS KMS"
        security-controls.io/in-transit: "TLS 1.3"
        security-controls.io/key-rotation: "30 days"
        security-controls.io/audit-logging: "enabled"
        security-controls.io/access-alerts: "enabled"
        security-controls.io/usage-analytics: "enabled"
        rbac-policies.io/enforced: "true"
        network-policies.io/level: "strict"
        backup.platform.io/enabled: "true"
        backup.platform.io/schedule: "daily"
        backup.platform.io/retention: "90 days"
    type: Opaque
    data:
      MQTT_BROKER_URL: "<base64>"
      MQTT_BROKER_USER: "<base64>"
      MQTT_BROKER_PASS: "<base64>"

  #################################################################################################
  # Secret: notification-service-secrets
  # Holds keys for FCM and APNs to send push notifications to clients. Strict rotation and
  # auditing are enforced to minimize unauthorized access to messaging services.
  #################################################################################################
  - apiVersion: v1
    kind: Secret
    metadata:
      name: notification-service-secrets
      namespace: notification-service
      labels:
        app: notification-service
        component: notification
        part-of: dog-walking-platform
        managed-by: platform-team
      annotations:
        rotation.kubernetes.io/trigger: "true"
        rotation.kubernetes.io/schedule: "720h"
        encryption.kubernetes.io/kms-key: "aws-kms-key-id"
        encryption.kubernetes.io/algorithm: "AES-256-GCM"
        encryption.kubernetes.io/provider: "AWS KMS"
        security-controls.io/in-transit: "TLS 1.3"
        security-controls.io/key-rotation: "30 days"
        security-controls.io/audit-logging: "enabled"
        security-controls.io/access-alerts: "enabled"
        security-controls.io/usage-analytics: "enabled"
        rbac-policies.io/enforced: "true"
        network-policies.io/level: "strict"
        backup.platform.io/enabled: "true"
        backup.platform.io/schedule: "daily"
        backup.platform.io/retention: "90 days"
    type: Opaque
    data:
      FCM_SERVER_KEY: "<base64>"
      APNS_CERT: "<base64>"
      APNS_KEY: "<base64>"

  #################################################################################################
  # Secret: monitoring-secrets
  # Houses monitoring and observability credentials, such as Datadog and Sentry keys. Ensures
  # performance metrics and error tracking data remain secure and accessible only to authorized
  # DevOps personnel.
  #################################################################################################
  - apiVersion: v1
    kind: Secret
    metadata:
      name: monitoring-secrets
      namespace: monitoring
      labels:
        app: monitoring
        component: monitoring
        part-of: dog-walking-platform
        managed-by: platform-team
      annotations:
        rotation.kubernetes.io/trigger: "true"
        rotation.kubernetes.io/schedule: "720h"
        encryption.kubernetes.io/kms-key: "aws-kms-key-id"
        encryption.kubernetes.io/algorithm: "AES-256-GCM"
        encryption.kubernetes.io/provider: "AWS KMS"
        security-controls.io/in-transit: "TLS 1.3"
        security-controls.io/key-rotation: "30 days"
        security-controls.io/audit-logging: "enabled"
        security-controls.io/access-alerts: "enabled"
        security-controls.io/usage-analytics: "enabled"
        rbac-policies.io/enforced: "true"
        network-policies.io/level: "strict"
        backup.platform.io/enabled: "true"
        backup.platform.io/schedule: "daily"
        backup.platform.io/retention: "90 days"
    type: Opaque
    data:
      DATADOG_API_KEY: "<base64>"
      SENTRY_DSN: "<base64>"